services:

#  proxy:
#    build: ./
#    networks:
#      - redmine
#    ports:
#      - "80:80"
#      - "443:443"

  postgres:
    image: postgres:16.2-bookworm
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=0QGcY+NH#d5X/YC'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:5.1.1-bookworm
    restart: always
    networks:
      - redmine
    volumes:
      - redmine-data:/usr/src/redmine/files
      - ./themes/purple-mine:/usr/src/redmine/public/themes/purple-mine
      - ./plugins:/usr/src/redmine/plugins
    ports:
      - "8080:3000"
    environment:
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=0QGcY+NH#d5X/YC'
      - 'REDMINE_PLUGINS_MIGRATE=true'
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge
